[tool.poetry]
name = "cp-library"
version = "0.1.0"
description = ""
authors = ["kobejean"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
online-judge-verify-helper = "^5.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
