import cp_library.math.table.__header__
from typing import Protocol
from cp_library.math.table.primes_cls import Primes

class SieveProtocol(Protocol):
    primes: Primes
    def factor_cnts(self, N): ...
    def factors(self, N): ...
    def unique_factors(self, N): ...
    def __getitem__(self, key) -> int: ...