import cp_library.ds.heap.__header__
from typing import Generic
from cp_library.misc.typing import _T

class HeapProtocol(Generic[_T]):
    def pop(self) -> _T: ...
    def push(self, item: _T): ...
    def pushpop(self, item: _T) -> _T: ...
    def replace(self, item: _T) -> _T: ...