import cp_library.ds.heap.__header__
from typing import Generic, TypeVar

T = TypeVar('T')
class HeapProtocol(Generic[T]):
    def pop(self) -> T: ...
    def push(self, item: T): ...
    def pushpop(self, item: T) -> T: ...
    def replace(self, item: T) -> T: ...