name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache
        df -h
    
    - name: Configure swap and system resources
      run: |
        # Configure swap
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo fallocate -l 8G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        
        # Optimize memory management
        sudo sysctl vm.swappiness=60
        sudo sysctl vm.vfs_cache_pressure=50
        
        # Show current memory state
        free -h
        df -h

    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 'pypy3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install with --no-deps first to avoid dependency conflicts
        pip install --no-deps -U git+https://github.com/${{ github.repository }}.git@main
        # Then install remaining dependencies
        pip install -r requirements.txt
      env:
        PIP_NO_CACHE_DIR: "false"
        PIP_DISABLE_PIP_VERSION_CHECK: "1"
        PYTHONUNBUFFERED: "1"

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        MALLOC_ARENA_MAX: "2"
        PYTHONMALLOC: "malloc"
        # Add memory limiting environment variables
        NODE_OPTIONS: "--max-old-space-size=4096"
        GRADLE_OPTS: "-Xmx4g"
      run: |
        # Clear system caches
        sudo sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches'
        
        # Monitor resources during test execution
        free -h
        df -h
        
        # Run tests with reduced parallelism and increased timeouts
        git pull && oj-verify all --tle 15 --timeout 7200 --jobs 1
        
        # Show final resource state
        free -h
        df -h