name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure swap space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo fallocate -l 16G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo swapon --show
        sudo sysctl vm.swappiness=80

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.10'

    - name: Create cache directories
      run: |
        mkdir -p ~/.cache/pip
        chmod -R 777 ~/.cache/pip

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Configure Python memory limits
      run: |
        echo "PYTHONMALLOC=debug" >> $GITHUB_ENV
        echo "PYTHONDEVMODE=1" >> $GITHUB_ENV
        echo "PYTHONASYNCIODEBUG=1" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -U git+https://github.com/${{ github.repository }}.git@main
      env:
        PIP_NO_CACHE_DIR: "false"
        PIP_DISABLE_PIP_VERSION_CHECK: "1"

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        MALLOC_ARENA_MAX: "2"
        PYTHONMALLOC: "malloc"
      run: |
        sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'
        
        # Add debug information
        echo "Available memory before tests:"
        free -h
        
        git pull && oj-verify all --tle 10 --timeout 6000 --jobs 1
        
        echo "Available memory after tests:"
        free -h