name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Free disk space
      run: |
        # More aggressive cleanup
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/lib/jvm
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt clean
    
    - name: Configure swap and system resources
      run: |
        # Configure swap
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo fallocate -l 16G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        
        # Optimize memory management
        sudo sysctl vm.swappiness=60
        sudo sysctl vm.vfs_cache_pressure=50
        
        # Show current memory state
        free -h
        df -h

    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 'pypy3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U git+https://github.com/${{ github.repository }}.git@main
      env:
        PIP_NO_CACHE_DIR: "false"
        PIP_DISABLE_PIP_VERSION_CHECK: "1"
        PYTHONUNBUFFERED: "1"

    - name: Set up Dropbox authentication
      env:
        DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
        DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
        DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      run: |
        python .github/workflows/dropbox_auth.py >> $GITHUB_ENV

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        DROPBOX_TOKEN: ${{ env.DROPBOX_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        # Clear system caches
        sudo sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches'
        
        git pull
        oj-verify run test/atcoder/**/*.py --tle 15 --timeout 7200 --jobs 6
        rm -rf .verify-helper/cache
        oj-verify run test/aoj/**/*.py --tle 15 --timeout 7200 --jobs 6
        rm -rf .verify-helper/cache
        oj-verify run test/library-checker/**/*.py --tle 15 --timeout 7200 --jobs 6
        rm -rf .verify-helper/cache
        oj-verify all --tle 15 --timeout 7200 --jobs 6
